// Expand the base Italian lexicon with topic/level batches generated by Claude.
// Idempotent: duplicates (same lemma+pos) are ignored on insert.
// Usage: node scripts/expand-lexicon.mjs
// Follow with: node scripts/generate-conjugations.mjs  (fills tables for new verbs)

import Anthropic from '@anthropic-ai/sdk';
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

function loadEnv(path) {
  try {
    for (const line of readFileSync(path, 'utf8').split('\n')) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].trim();
    }
  } catch {
    /* rely on exported vars */
  }
}
loadEnv(resolve(process.cwd(), '.env'));

const { EXPO_PUBLIC_SUPABASE_URL: url, SUPABASE_SERVICE_ROLE_KEY: serviceKey } = process.env;
if (!url || !serviceKey || !process.env.ANTHROPIC_API_KEY) {
  console.error('Missing env vars (see .env.example)');
  process.exit(1);
}
const supabase = createClient(url, serviceKey);
const anthropic = new Anthropic();

const POS = ['verb', 'noun', 'adj', 'adv', 'prep', 'pron', 'conj', 'interj', 'phrase'];

const BATCHES = [
  ['greetings, politeness and everyday phrases', 'A1'],
  ['numbers, quantities and measurements', 'A1'],
  ['time: days, months, seasons, telling time', 'A1'],
  ['family, people and relationships', 'A1'],
  ['colors, shapes and basic descriptions', 'A1'],
  ['food and drink', 'A1'],
  ['house, rooms and furniture', 'A1'],
  ['city, places and directions', 'A1'],
  ['travel and transport', 'A1'],
  ['clothing and accessories', 'A1'],
  ['body and health', 'A1'],
  ['weather and nature', 'A1'],
  ['animals', 'A1'],
  ['school, office and stationery', 'A1'],
  ['daily routine verbs', 'A1'],
  ['essential adjectives', 'A1'],
  ['work and professions', 'A2'],
  ['shopping and money', 'A2'],
  ['sports and hobbies', 'A2'],
  ['technology, phone and media', 'A2'],
  ['emotions and personality', 'A2'],
  ['frequent verbs', 'A2'],
  ['frequent adjectives and adverbs', 'A2'],
  ['restaurant, cooking and kitchen', 'A2'],
  ['frequent verbs', 'B1'],
  ['abstract nouns (society, ideas, feelings)', 'B1'],
  ['opinion, discussion and connectors', 'B1'],
  ['descriptive adjectives and adverbs', 'B1'],
];

// Structured outputs reject `type: [..., 'null'] + enum` — use anyOf instead
const nullableEnum = (values) => ({ anyOf: [{ type: 'string', enum: values }, { type: 'null' }] });

const entrySchema = {
  type: 'object',
  additionalProperties: false,
  required: ['lemma', 'pos', 'gender', 'auxiliary', 'is_irregular', 'translations'],
  properties: {
    lemma: { type: 'string' },
    pos: { type: 'string', enum: POS },
    gender: nullableEnum(['m', 'f']),
    auxiliary: nullableEnum(['essere', 'avere']),
    is_irregular: { type: 'boolean' },
    translations: { type: 'array', items: { type: 'string' }, minItems: 1 },
  },
};
const outputSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['words'],
  properties: { words: { type: 'array', items: entrySchema } },
};

const normalize = (s) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '');

async function generateBatch(topic, cefr) {
  const response = await anthropic.messages.create({
    model: 'claude-opus-4-8',
    max_tokens: 8000,
    thinking: { type: 'adaptive' },
    output_config: { format: { type: 'json_schema', schema: outputSchema } },
    messages: [
      {
        role: 'user',
        content:
          `List the ~40 most useful Italian dictionary words for the topic "${topic}" ` +
          `at CEFR level ${cefr}, for an English-speaking learner. Rules: ` +
          `lemma is the dictionary form, lowercase (infinitive for verbs, singular for nouns), no articles; ` +
          `nouns MUST have gender (m/f), other pos gender null; ` +
          `verbs MUST have their passato-prossimo auxiliary (essere/avere; pick the most common for dual-aux verbs), other pos null; ` +
          `1-3 accurate English translations each; prefer single words (short fixed phrases allowed as pos "phrase").`,
      },
    ],
  });
  const text = response.content.find((b) => b.type === 'text')?.text ?? '';
  return JSON.parse(text).words;
}

let inserted = 0,
  skipped = 0,
  failedBatches = 0;
const CONCURRENCY = 3;
for (let i = 0; i < BATCHES.length; i += CONCURRENCY) {
  const group = BATCHES.slice(i, i + CONCURRENCY);
  await Promise.all(
    group.map(async ([topic, cefr]) => {
      try {
        const words = await generateBatch(topic, cefr);
        const valid = words.filter(
          (w) =>
            w.lemma?.trim() &&
            POS.includes(w.pos) &&
            (w.pos !== 'noun' || ['m', 'f'].includes(w.gender)) &&
            (w.pos !== 'verb' || ['essere', 'avere'].includes(w.auxiliary)) &&
            w.translations?.length,
        );
        const { data, error } = await supabase
          .from('lexicon_entries')
          .upsert(
            valid.map((w) => ({
              target_language: 'it',
              lemma: w.lemma.trim().toLowerCase(),
              normalized: normalize(w.lemma),
              pos: w.pos,
              gender: w.pos === 'noun' ? w.gender : null,
              auxiliary: w.pos === 'verb' ? w.auxiliary : null,
              is_irregular: w.is_irregular ?? false,
              cefr,
              frequency_rank: null,
              source: 'ai',
            })),
            { onConflict: 'target_language,lemma,pos', ignoreDuplicates: true },
          )
          .select('id, lemma');
        if (error) throw new Error(error.message);

        const newRows = data ?? [];
        const byLemma = new Map(valid.map((w) => [w.lemma.trim().toLowerCase(), w]));
        const trRows = newRows.flatMap((row) =>
          (byLemma.get(row.lemma)?.translations ?? []).map((t, order) => ({
            entry_id: row.id,
            source_language: 'en',
            translation: t,
            sense_order: order,
          })),
        );
        if (trRows.length) {
          const { error: trErr } = await supabase.from('lexicon_translations').insert(trRows);
          if (trErr) throw new Error(trErr.message);
        }
        inserted += newRows.length;
        skipped += valid.length - newRows.length;
        console.log(`✓ ${topic} (${cefr}): +${newRows.length} new, ${valid.length - newRows.length} dupes`);
      } catch (e) {
        failedBatches++;
        console.error(`✗ ${topic} (${cefr}): ${e.message}`);
      }
    }),
  );
}

const { count } = await supabase
  .from('lexicon_entries')
  .select('*', { count: 'exact', head: true });
console.log(`Done: +${inserted} new entries, ${skipped} duplicates skipped, ${failedBatches} failed batches.`);
console.log(`Lexicon total: ${count} entries.`);
